const TraditionalColor = {
  // @色定数
  '藍色': {type: 'const', value: '#165E83'}, // @あいいろ
  '藍媚茶': {type: 'const', value: '#555647'}, // @あいこびちゃ
  '藍白': {type: 'const', value: '#EBF6F7'}, // @あいじろ
  '藍墨茶': {type: 'const', value: '#474A4D'}, // @あいすみちゃ
  '藍鉄': {type: 'const', value: '#393F4C'}, // @あいてつ
  '藍鼠': {type: 'const', value: '#6C848D'}, // @あいねず
  '藍海松茶': {type: 'const', value: '#56564B'}, // @あいみるちゃ
  '碧': {type: 'const', value: '#0095D9'}, // @あお
  '青褐': {type: 'const', value: '#393E4F'}, // @あおかち
  '青朽葉': {type: 'const', value: '#ADA250'}, // @あおくちば
  '青白橡': {type: 'const', value: '#9BA88D'}, // @あおしろつるばみ
  '青竹色': {type: 'const', value: '#7EBEAB'}, // @あおたけいろ
  '青丹': {type: 'const', value: '#99AB4E'}, // @あおに
  '青鈍': {type: 'const', value: '#6B7B6E'}, // @あおにび
  '青藤色': {type: 'const', value: '#84A2D4'}, // @あおふじいろ
  '青緑': {type: 'const', value: '#00A497'}, // @あおみどり
  '青紫': {type: 'const', value: '#674598'}, // @あおむらさき
  '朱': {type: 'const', value: '#E60033'}, // @あか
  '赤朽葉色': {type: 'const', value: '#DB8449'}, // @あかくちばいろ
  '赤香': {type: 'const', value: '#F6B894'}, // @あかこう
  '赤錆色': {type: 'const', value: '#8A3319'}, // @あかさびいろ
  '赤白橡': {type: 'const', value: '#D7A98C'}, // @あかしろつるばみ
  '赤墨': {type: 'const', value: '#3F312B'}, // @あかすみ
  '赤橙': {type: 'const', value: '#E65226'}, // @あかだいだい
  '赤茶': {type: 'const', value: '#BB5535'}, // @あかちゃ
  '暁鼠': {type: 'const', value: '#D3CFD9'}, // @あかつきねず
  '赤丹': {type: 'const', value: '#CE5242'}, // @あかに
  '茜色': {type: 'const', value: '#B7282E'}, // @あかねいろ
  '赤紅': {type: 'const', value: '#C53D43'}, // @あかべに
  '赤紫': {type: 'const', value: '#EB6EA5'}, // @あかむらさき
  '灰汁色': {type: 'const', value: '#9E9478'}, // @あくいろ
  '真緋': {type: 'const', value: '#BA2636'}, // @あけ
  '曙色': {type: 'const', value: '#F09685'}, // @あけぼのいろ
  '浅葱色': {type: 'const', value: '#00A3AF'}, // @あさぎいろ
  '浅蘇芳': {type: 'const', value: '#A25768'}, // @あさすおう
  '浅縹': {type: 'const', value: '#84B9CB'}, // @あさはなだ
  '浅緑': {type: 'const', value: '#88CB7F'}, // @あさみどり
  '浅紫': {type: 'const', value: '#C4A3BF'}, // @あさむらさき
  '紫陽花青': {type: 'const', value: '#9093E0'}, // @あじさいあお
  '小豆色': {type: 'const', value: '#96514D'}, // @あずきいろ
  '小豆茶': {type: 'const', value: '#6B3E3F'}, // @あずきちゃ
  '油色': {type: 'const', value: '#A19361'}, // @あぶらいろ
  '亜麻色': {type: 'const', value: '#D6C6AF'}, // @あまいろ
  '天色': {type: 'const', value: '#2CA9E1'}, // @あまいろ
  '飴色': {type: 'const', value: '#DEB068'}, // @あめいろ
  '菖蒲色': {type: 'const', value: '#CC7EB1'}, // @あやめいろ
  '洗柿': {type: 'const', value: '#F2C9AC'}, // @あらいがき
  '洗朱': {type: 'const', value: '#D0826C'}, // @あらいしゅ
  '退紅': {type: 'const', value: '#D69090'}, // @あらぞめ
  '淡藤色': {type: 'const', value: '#BBC8E6'}, // @あわふじいろ
  '淡紅藤': {type: 'const', value: '#E6CDE3'}, // @あわべにふじ
  '暗紅色': {type: 'const', value: '#74325C'}, // @あんこうしょく
  '暗黒色': {type: 'const', value: '#16160E'}, // @あんこくしょく
  '杏色': {type: 'const', value: '#F7B977'}, // @あんずいろ
  '一斤染': {type: 'const', value: '#F5B199'}, // @いっこんぞめ
  '今様色': {type: 'const', value: '#D0576B'}, // @いまよういろ
  '岩井茶': {type: 'const', value: '#6B6F59'}, // @いわいちゃ
  '鶯色': {type: 'const', value: '#928C36'}, // @うぐいすいろ
  '鶯茶': {type: 'const', value: '#715C1F'}, // @うぐいすちゃ
  '鬱金色': {type: 'const', value: '#FABF14'}, // @うこんいろ
  '薄藍': {type: 'const', value: '#0094C8'}, // @うすあい
  '薄青': {type: 'const', value: '#93B69C'}, // @うすあお
  '薄色': {type: 'const', value: '#A89DAC'}, // @うすいろ
  '薄梅鼠': {type: 'const', value: '#DCD6D9'}, // @うすうめねず
  '薄柿': {type: 'const', value: '#D4ACAD'}, // @うすがき
  '浅黄': {type: 'const', value: '#EDD3A1'}, // @うすき
  '浅緋': {type: 'const', value: '#DF7163'}, // @うすきひ
  '薄雲鼠': {type: 'const', value: '#D4DCDA'}, // @うすくもねず
  '薄群青': {type: 'const', value: '#5383C3'}, // @うすぐんじょう
  '淡香': {type: 'const', value: '#F3BF88'}, // @うすこう
  '薄香': {type: 'const', value: '#F0CFA0'}, // @うすこう
  '薄紅梅': {type: 'const', value: '#E597B2'}, // @うすこうばい
  '薄桜': {type: 'const', value: '#FDEFF2'}, // @うすざくら
  '薄墨色': {type: 'const', value: '#A3A3A2'}, // @うすずみいろ
  '薄卵色': {type: 'const', value: '#FDE8D0'}, // @うすたまごいろ
  '薄鈍': {type: 'const', value: '#ADADAD'}, // @うすにび
  '薄鼠': {type: 'const', value: '#9790A4'}, // @うすねず
  '薄花色': {type: 'const', value: '#698AAB'}, // @うすはないろ
  '薄花桜': {type: 'const', value: '#5A79BA'}, // @うすはなざくら
  '薄縹': {type: 'const', value: '#507EA4'}, // @うすはなだ
  '薄葡萄': {type: 'const', value: '#C0A2C7'}, // @うすぶどう
  '薄紅': {type: 'const', value: '#F0908D'}, // @うすべに
  '薄緑': {type: 'const', value: '#69B076'}, // @うすみどり
  '淡萌黄': {type: 'const', value: '#93CA76'}, // @うすもえぎ
  '薄萌葱': {type: 'const', value: '#BADCAD'}, // @うすもえぎ
  '空五倍子色': {type: 'const', value: '#9D896C'}, // @うつぶしいろ
  '卯花色': {type: 'const', value: '#F7FCFE'}, // @うのはないろ
  '梅染': {type: 'const', value: '#B48A76'}, // @うめぞめ
  '梅鼠': {type: 'const', value: '#C099A0'}, // @うめねず
  '梅紫': {type: 'const', value: '#AA4C8F'}, // @うめむらさき
  '裏葉柳': {type: 'const', value: '#C1D8AC'}, // @うらはやなぎ
  '潤色': {type: 'const', value: '#C8C2BE'}, // @うるみいろ
  '江戸茶': {type: 'const', value: '#CD8C5C'}, // @えどちゃ
  '江戸鼠': {type: 'const', value: '#928178'}, // @えどねず
  '江戸紫': {type: 'const', value: '#745399'}, // @えどむらさき
  '葡萄色': {type: 'const', value: '#640125'}, // @えびいろ
  '蒲葡': {type: 'const', value: '#7A4171'}, // @えびぞめ
  '葡萄茶': {type: 'const', value: '#6C2C2F'}, // @えびちゃ
  '海老茶': {type: 'const', value: '#773C30'}, // @えびちゃ
  '遠州茶': {type: 'const', value: '#CA8269'}, // @えんしゅうちゃ
  '臙脂': {type: 'const', value: '#B94047'}, // @えんじ
  '鉛丹色': {type: 'const', value: '#EC6D51'}, // @えんたんいろ
  '老竹色': {type: 'const', value: '#769164'}, // @おいたけいろ
  '樗色': {type: 'const', value: '#7A71A2'}, // @おうちいろ
  '黄土色': {type: 'const', value: '#C39143'}, // @おうどいろ
  '黄丹': {type: 'const', value: '#EE7948'}, // @おうに
  '女郎花': {type: 'const', value: '#F2F2B0'}, // @おみなえし
  '御召御納戸': {type: 'const', value: '#4C6473'}, // @おめしおなんど
  '御召茶': {type: 'const', value: '#43676B'}, // @おめしちゃ
  '思色': {type: 'const', value: '#D91E10'}, // @おもいいろ
  '灰白色': {type: 'const', value: '#E9E4D4'}, // @かいはくしょく
  '柿色': {type: 'const', value: '#ED6D3D'}, // @かきいろ
  '柿渋色': {type: 'const', value: '#9D5A52'}, // @かきしぶいろ
  '柿茶': {type: 'const', value: '#954E2A'}, // @かきちゃ
  '杜若色': {type: 'const', value: '#3E62AD'}, // @かきつばたいろ
  '霞色': {type: 'const', value: '#C8C2C6'}, // @かすみいろ
  '褐色': {type: 'const', value: '#4D4C61'}, // @かちいろ
  '褐返': {type: 'const', value: '#203744'}, // @かちかえし
  '褐色': {type: 'const', value: '#8A3B00'}, // @かっしょく
  '金糸雀色': {type: 'const', value: '#EBD842'}, // @かなりあいろ
  '樺色': {type: 'const', value: '#CD5E3C'}, // @かばいろ
  '樺茶色': {type: 'const', value: '#726250'}, // @かばちゃいろ
  '瓶覗': {type: 'const', value: '#A2D7DD'}, // @かめのぞき
  '韓紅': {type: 'const', value: '#E95464'}, // @からくれない
  '芥子色': {type: 'const', value: '#D0AF4C'}, // @からしいろ
  '烏羽色': {type: 'const', value: '#180614'}, // @からすばいろ
  '唐茶': {type: 'const', value: '#783C1D'}, // @からちゃ
  '枯茶': {type: 'const', value: '#8D6449'}, // @からちゃ
  '刈安色': {type: 'const', value: '#F5E56B'}, // @かりやすいろ
  '枯色': {type: 'const', value: '#E0C38C'}, // @かれいろ
  '枯草色': {type: 'const', value: '#E4DC8A'}, // @かれくさいろ
  '枯野色': {type: 'const', value: '#D3CBC6'}, // @かれのいろ
  '革色': {type: 'const', value: '#475950'}, // @かわいろ
  '土器色': {type: 'const', value: '#C37854'}, // @かわらけいろ
  '萱草色': {type: 'const', value: '#F8B862'}, // @かんぞういろ
  '黄赤': {type: 'const', value: '#D86011'}, // @きあか
  '黄唐茶': {type: 'const', value: '#B98C46'}, // @きがらちゃ
  '黄枯茶': {type: 'const', value: '#765C47'}, // @きがらちゃ
  '桔梗色': {type: 'const', value: '#5654A2'}, // @ききょういろ
  '桔梗鼠': {type: 'const', value: '#95949A'}, // @ききょうねず
  '麹塵': {type: 'const', value: '#6E7955'}, // @きくじん
  '黄支子色': {type: 'const', value: '#FFDB4F'}, // @きくちなしいろ
  '黄朽葉色': {type: 'const', value: '#D3A243'}, // @きくちばいろ
  '黄水仙': {type: 'const', value: '#F2D675'}, // @きずいせん
  '黄茶': {type: 'const', value: '#E17B34'}, // @きちゃ
  '狐色': {type: 'const', value: '#C38743'}, // @きつねいろ
  '黄橡': {type: 'const', value: '#B68D4C'}, // @きつるばみ
  '生成色': {type: 'const', value: '#FBFAF5'}, // @きなりいろ
  '絹鼠': {type: 'const', value: '#DDDCD6'}, // @きぬねず
  '黄檗色': {type: 'const', value: '#FEF263'}, // @きはだいろ
  '黄緑': {type: 'const', value: '#B8D200'}, // @きみどり
  '黄海松茶': {type: 'const', value: '#918754'}, // @きみるちゃ
  '伽羅色': {type: 'const', value: '#D8A373'}, // @きゃらいろ
  '京紫': {type: 'const', value: '#9D5B8B'}, // @きょうむらさき
  '金赤': {type: 'const', value: '#EA5506'}, // @きんあか
  '金茶': {type: 'const', value: '#F39800'}, // @きんちゃ
  '銀朱': {type: 'const', value: '#C85554'}, // @ぎんしゅ
  '銀煤竹': {type: 'const', value: '#856859'}, // @ぎんすすだけ
  '銀鼠': {type: 'const', value: '#AFAFB0'}, // @ぎんねず
  '草色': {type: 'const', value: '#7B8D42'}, // @くさいろ
  '支子色': {type: 'const', value: '#FBCA4D'}, // @くちなしいろ
  '朽葉色': {type: 'const', value: '#917347'}, // @くちばいろ
  '栗色': {type: 'const', value: '#762F07'}, // @くりいろ
  '涅色': {type: 'const', value: '#554738'}, // @くりいろ
  '栗梅': {type: 'const', value: '#852E19'}, // @くりうめ
  '栗皮茶': {type: 'const', value: '#6D3C32'}, // @くりかわちゃ
  '胡桃色': {type: 'const', value: '#A86F4C'}, // @くるみいろ
  '胡桃染': {type: 'const', value: '#A58F86'}, // @くるみぞめ
  '紅': {type: 'const', value: '#D7003A'}, // @くれない
  '黒': {type: 'const', value: '#2A2A2A'}, // @くろ
  '黒茶': {type: 'const', value: '#583822'}, // @くろちゃ
  '黒橡': {type: 'const', value: '#544A47'}, // @くろつるばみ
  '黒鳶': {type: 'const', value: '#432F2F'}, // @くろとび
  '黒紅': {type: 'const', value: '#302833'}, // @くろべに
  '黒緑': {type: 'const', value: '#333631'}, // @くろみどり
  '桑染': {type: 'const', value: '#B79B5B'}, // @くわぞめ
  '桑茶': {type: 'const', value: '#956F29'}, // @くわちゃ
  '桑実色': {type: 'const', value: '#55295B'}, // @くわのみいろ
  '群青色': {type: 'const', value: '#4C6CB3'}, // @ぐんじょういろ
  '消炭色': {type: 'const', value: '#524E4D'}, // @けしずみいろ
  '滅紫': {type: 'const', value: '#594255'}, // @けしむらさき
  '憲法色': {type: 'const', value: '#543F32'}, // @けんぽういろ
  '憲法黒茶': {type: 'const', value: '#241A08'}, // @けんぽうくろちゃ
  '月白': {type: 'const', value: '#EAF4FC'}, // @げっぱく
  '源氏鼠': {type: 'const', value: '#888084'}, // @げんじねず
  '濃藍': {type: 'const', value: '#0F2350'}, // @こいあい
  '濃鼠': {type: 'const', value: '#4F455C'}, // @こいねず
  '香色': {type: 'const', value: '#EFCD9A'}, // @こういろ
  '光悦茶': {type: 'const', value: '#773328'}, // @こうえつちゃ
  '柑子色': {type: 'const', value: '#F6AD49'}, // @こうじいろ
  '香染': {type: 'const', value: '#AD7D4C'}, // @こうぞめ
  '紅梅色': {type: 'const', value: '#F2A0A1'}, // @こうばいいろ
  '高麗納戸': {type: 'const', value: '#2C4F54'}, // @こうらいなんど
  '黄櫨染': {type: 'const', value: '#D66A35'}, // @こうろぜん
  '黄金': {type: 'const', value: '#E6B422'}, // @こがね
  '焦香': {type: 'const', value: '#AE7C58'}, // @こがれこう
  '濃色': {type: 'const', value: '#634950'}, // @こきいろ
  '深支子': {type: 'const', value: '#EB9B6F'}, // @こきくちなし
  '深縹': {type: 'const', value: '#2A4073'}, // @こきはなだ
  '深緋': {type: 'const', value: '#C9171E'}, // @こきひ
  '黒壇': {type: 'const', value: '#250D00'}, // @こくたん
  '国防色': {type: 'const', value: '#7B6C3E'}, // @こくぼうしょく
  '苔色': {type: 'const', value: '#69821B'}, // @こけいろ
  '焦茶': {type: 'const', value: '#6F4B3E'}, // @こげちゃ
  '古代紫': {type: 'const', value: '#895B8A'}, // @こだいむらさき
  '琥珀色': {type: 'const', value: '#BF783A'}, // @こはくいろ
  '媚茶': {type: 'const', value: '#716246'}, // @こびちゃ
  '小麦色': {type: 'const', value: '#E49E61'}, // @こむぎいろ
  '紺藍': {type: 'const', value: '#4A488E'}, // @こんあい
  '紺色': {type: 'const', value: '#223A70'}, // @こんいろ
  '紺桔梗': {type: 'const', value: '#1F2C63'}, // @こんききょう
  '紺青': {type: 'const', value: '#192F60'}, // @こんじょう
  '紺鼠': {type: 'const', value: '#44617B'}, // @こんねず
  '紺碧': {type: 'const', value: '#007BBB'}, // @こんぺき
  '紺瑠璃': {type: 'const', value: '#164A84'}, // @こんるり
  '胡粉色': {type: 'const', value: '#FFFFFC'}, // @ごふんいろ
  '桜色': {type: 'const', value: '#FEF4F4'}, // @さくらいろ
  '桜鼠': {type: 'const', value: '#E9DFE5'}, // @さくらねず
  '錆浅葱': {type: 'const', value: '#5C9291'}, // @さびあさぎ
  '錆色': {type: 'const', value: '#6C3524'}, // @さびいろ
  '錆御納戸': {type: 'const', value: '#53727D'}, // @さびおなんど
  '錆青磁': {type: 'const', value: '#A6C8B2'}, // @さびせいじ
  '錆鉄御納戸': {type: 'const', value: '#485859'}, // @さびてつおなんど
  '錆鼠': {type: 'const', value: '#47585C'}, // @さびねず
  '珊瑚色': {type: 'const', value: '#F5B1AA'}, // @さんごいろ
  '珊瑚朱色': {type: 'const', value: '#EE836F'}, // @さんごしゅいろ
  '紫苑色': {type: 'const', value: '#867BA9'}, // @しおんいろ
  '芝翫茶': {type: 'const', value: '#AD7E4E'}, // @しかんちゃ
  '紫黒': {type: 'const', value: '#2E2930'}, // @しこく
  '紫紺': {type: 'const', value: '#460E44'}, // @しこん
  '宍色': {type: 'const', value: '#EFAB93'}, // @ししいろ
  '漆黒': {type: 'const', value: '#0D0015'}, // @しっこく
  '紫土': {type: 'const', value: '#753035'}, // @しど
  '東雲色': {type: 'const', value: '#F19072'}, // @しののめいろ
  '渋紙色': {type: 'const', value: '#946243'}, // @しぶかみいろ
  '赤銅色': {type: 'const', value: '#752100'}, // @しゃくどういろ
  '洒落柿': {type: 'const', value: '#F7BD8F'}, // @しゃれがき
  '朱色': {type: 'const', value: '#EB6101'}, // @しゅいろ
  '朱土生壁': {type: 'const', value: '#915847'}, // @しゅどなまかべ
  '猩猩緋': {type: 'const', value: '#E2041B'}, // @しょうじょうひ(猩々緋。々が使えない)
  '菖蒲色': {type: 'const', value: '#674196'}, // @しょうぶいろ
  '白藍': {type: 'const', value: '#C1E4E9'}, // @しらあい
  '白梅鼠': {type: 'const', value: '#E5E4E6'}, // @しらうめねず
  '白茶': {type: 'const', value: '#DDBB99'}, // @しらちゃ
  '白花色': {type: 'const', value: '#E8ECEF'}, // @しらはないろ
  '白藤色': {type: 'const', value: '#DBD0E6'}, // @しらふじいろ
  '白菫色': {type: 'const', value: '#EAEDF7'}, // @しろすみれいろ
  '白橡': {type: 'const', value: '#CBB994'}, // @しろつるばみ
  '白鼠': {type: 'const', value: '#DCDDDD'}, // @しろねず
  '白練': {type: 'const', value: '#F3F3F2'}, // @しろねり
  '真紅': {type: 'const', value: '#A22041'}, // @しんく
  '新橋色': {type: 'const', value: '#59B9C6'}, // @しんばしいろ
  '甚三紅': {type: 'const', value: '#EE827C'}, // @じんざもみ
  '蘇芳': {type: 'const', value: '#9E3D3F'}, // @すおう
  '蘇芳香': {type: 'const', value: '#A86965'}, // @すおうこう
  '煤色': {type: 'const', value: '#887F7A'}, // @すすいろ
  '煤竹色': {type: 'const', value: '#6F514C'}, // @すすたけいろ
  '錫色': {type: 'const', value: '#9EA1A3'}, // @すずいろ
  '雀茶': {type: 'const', value: '#AA4F37'}, // @すずめちゃ
  '砂色': {type: 'const', value: '#DCD3B2'}, // @すないろ
  '素鼠': {type: 'const', value: '#9FA0A0'}, // @すねずみ
  '炭': {type: 'const', value: '#343434'}, // @すみ
  '墨': {type: 'const', value: '#595857'}, // @すみ
  '菫色': {type: 'const', value: '#7058A3'}, // @すみれいろ
  '青磁色': {type: 'const', value: '#7EBEA5'}, // @せいじいろ
  '青磁鼠': {type: 'const', value: '#BED2C3'}, // @せいじねず
  '青碧': {type: 'const', value: '#478384'}, // @せいへき
  '青藍': {type: 'const', value: '#274A78'}, // @せいらん
  '石竹色': {type: 'const', value: '#E5ABBE'}, // @せきちくいろ
  '赤褐色': {type: 'const', value: '#683F36'}, // @せっかっしょく
  '雪白': {type: 'const', value: '#FCFFFE'}, // @せっぱく
  '仙斎茶': {type: 'const', value: '#474B42'}, // @せんさいちゃ
  '千歳茶': {type: 'const', value: '#494A41'}, // @せんさいちゃ
  '煎茶色': {type: 'const', value: '#8C6450'}, // @せんちゃいろ
  '宗伝唐茶': {type: 'const', value: '#A16D5D'}, // @そうでんからちゃ
  '素色': {type: 'const', value: '#EAE5E3'}, // @そしょく
  '蕎麦切色': {type: 'const', value: '#D4DCD6'}, // @そばきりいろ
  '纁': {type: 'const', value: '#E0815E'}, // @そひ
  '赭': {type: 'const', value: '#AB6953'}, // @そほ
  '空色': {type: 'const', value: '#A0D8EF'}, // @そらいろ
  '象牙色': {type: 'const', value: '#F8F4E6'}, // @ぞうげいろ
  '代赭': {type: 'const', value: '#BB5520'}, // @たいしゃ
  '卵色': {type: 'const', value: '#FCD575'}, // @たまごいろ
  '淡黄': {type: 'const', value: '#F8E58C'}, // @たんこう
  '蒲公英色': {type: 'const', value: '#FFD900'}, // @たんぽぽいろ
  '橙色': {type: 'const', value: '#EE7800'}, // @だいだいいろ
  '団十郎茶': {type: 'const', value: '#9F563A'}, // @だんじゅうろうちゃ
  '千草色': {type: 'const', value: '#92B5A9'}, // @ちぐさいろ
  '千草鼠': {type: 'const', value: '#BED3CA'}, // @ちぐさねず
  '千歳緑': {type: 'const', value: '#316745'}, // @ちとせみどり
  '茶色': {type: 'const', value: '#965042'}, // @ちゃいろ
  '茶褐色': {type: 'const', value: '#664032'}, // @ちゃかっしょく
  '茶鼠': {type: 'const', value: '#A99E93'}, // @ちゃねずみ
  '中黄': {type: 'const', value: '#FFEA00'}, // @ちゅうき
  '長春色': {type: 'const', value: '#C97586'}, // @ちょうしゅんいろ
  '丁字染': {type: 'const', value: '#AE7C4B'}, // @ちょうじぞめ
  '丁子茶': {type: 'const', value: '#B4866B'}, // @ちょうじちゃ
  '桃染色': {type: 'const', value: '#EB94AA'}, // @つきいろ
  '土色': {type: 'const', value: '#BC763C'}, // @つちいろ
  '躑躅色': {type: 'const', value: '#E95295'}, // @つつじいろ
  '露草色': {type: 'const', value: '#38A1DB'}, // @つゆくさいろ
  '鉄色': {type: 'const', value: '#005243'}, // @てついろ
  '鉄御納戸': {type: 'const', value: '#455765'}, // @てつおなんど
  '鉄黒': {type: 'const', value: '#281A14'}, // @てつぐろ
  '鉄紺': {type: 'const', value: '#17184B'}, // @てつこん
  '照柿': {type: 'const', value: '#EB6238'}, // @てりがき
  '藤黄': {type: 'const', value: '#F7C114'}, // @とうおう
  '玉蜀黍色': {type: 'const', value: '#EEC362'}, // @とうもろこしいろ
  '鴇浅葱': {type: 'const', value: '#B88884'}, // @ときあさぎ
  '鴇色': {type: 'const', value: '#F4B3C2'}, // @ときいろ
  '鴇唐茶': {type: 'const', value: '#E09E87'}, // @ときがらちゃ
  '鴇鼠': {type: 'const', value: '#E4D2D8'}, // @ときねず
  '鴇羽色': {type: 'const', value: '#ECAAAB'}, // @ときはいろ
  '常磐色': {type: 'const', value: '#007B43'}, // @ときわいろ
  '常磐緑': {type: 'const', value: '#028760'}, // @ときわみどり
  '木賊色': {type: 'const', value: '#3B7960'}, // @とくさいろ
  '砥粉色': {type: 'const', value: '#F4DDA5'}, // @とのこいろ
  '沈香茶': {type: 'const', value: '#657F79'}, // @とのちゃ
  '砺茶': {type: 'const', value: '#9F6F55'}, // @とのちゃ
  '鳶色': {type: 'const', value: '#95483F'}, // @とびいろ
  '留紺': {type: 'const', value: '#1C305C'}, // @とめこん
  '鳥子色': {type: 'const', value: '#FFF1CF'}, // @とりのこいろ
  '丼鼠': {type: 'const', value: '#595455'}, // @どぶねずみ
  '苗色': {type: 'const', value: '#B0CA71'}, // @なえいろ
  '中紅花': {type: 'const', value: '#E891A3'}, // @なかのくれない
  '中紅': {type: 'const', value: '#C85179'}, // @なかべに
  '茄子紺': {type: 'const', value: '#824880'}, // @なすこん
  '菜種油色': {type: 'const', value: '#A69425'}, // @なたねゆいろ
  '夏虫色': {type: 'const', value: '#CEE4AE'}, // @なつむしいろ
  '撫子色': {type: 'const', value: '#EEBBCB'}, // @なでしこいろ
  '菜花色': {type: 'const', value: '#FFEC47'}, // @なのはないろ
  '生壁色': {type: 'const', value: '#94846A'}, // @なまかべいろ
  '鉛色': {type: 'const', value: '#7B7C7D'}, // @なまりいろ
  '納戸色': {type: 'const', value: '#008899'}, // @なんどいろ
  '丹色': {type: 'const', value: '#E45E32'}, // @にいろ
  '虹色': {type: 'const', value: '#F6BFBC'}, // @にじいろ
  '似紫': {type: 'const', value: '#513743'}, // @にせむらさき
  '肉桂色': {type: 'const', value: '#DD7A56'}, // @にっけいいろ
  '鈍色': {type: 'const', value: '#727171'}, // @にびいろ
  '乳白色': {type: 'const', value: '#F3F3F3'}, // @にゅうはくしょく
  '人参色': {type: 'const', value: '#EC6800'}, // @にんじんいろ
  '濡羽色': {type: 'const', value: '#000B00'}, // @ぬればいろ
  '根岸色': {type: 'const', value: '#938B4B'}, // @ねぎしいろ
  '鼠色': {type: 'const', value: '#949495'}, // @ねずみいろ
  '練色': {type: 'const', value: '#EDE4CD'}, // @ねりいろ
  '熨斗目花色': {type: 'const', value: '#426579'}, // @のしめはないろ
  '灰青': {type: 'const', value: '#C0C6C9'}, // @はいあお
  '灰色': {type: 'const', value: '#7D7D7D'}, // @はいいろ
  '灰梅': {type: 'const', value: '#E8D3C7'}, // @はいうめ
  '灰黄緑': {type: 'const', value: '#E6EAE3'}, // @はいきみどり
  '灰桜': {type: 'const', value: '#E8D3D1'}, // @はいざくら
  '灰茶': {type: 'const', value: '#98623C'}, // @はいちゃ
  '萩色': {type: 'const', value: '#CF747B'}, // @はぎいろ
  '白磁': {type: 'const', value: '#F8FBF8'}, // @はくじ
  '半色': {type: 'const', value: '#A69ABD'}, // @はしたいろ
  '榛色': {type: 'const', value: '#BFA46F'}, // @はしばみいろ
  '櫨色': {type: 'const', value: '#B77B57'}, // @はじいろ
  '櫨染': {type: 'const', value: '#D9A62E'}, // @はじぞめ
  '肌色': {type: 'const', value: '#FCE2C4'}, // @はだいろ
  '蜂蜜色': {type: 'const', value: '#FDDEA5'}, // @はちみついろ
  '鳩羽色': {type: 'const', value: '#95859C'}, // @はとばいろ
  '鳩羽鼠': {type: 'const', value: '#9E8B8E'}, // @はとばねずみ
  '花浅葱': {type: 'const', value: '#2A83A2'}, // @はなあさぎ
  '花色': {type: 'const', value: '#4D5AAF'}, // @はないろ
  '縹色': {type: 'const', value: '#2792C3'}, // @はなだいろ
  '花葉色': {type: 'const', value: '#FBD26B'}, // @はなばいろ
  '花緑青': {type: 'const', value: '#00A381'}, // @はなろくしょう
  '朱華': {type: 'const', value: '#DF9D9F'}, // @はねず
  '梅幸茶': {type: 'const', value: '#887938'}, // @ばいこうちゃ
  '薔薇色': {type: 'const', value: '#E9546B'}, // @ばらいろ
  '緋色': {type: 'const', value: '#D3381C'}, // @ひいろ
  '肥後煤竹': {type: 'const', value: '#897858'}, // @ひごすすたけ
  '翡翠色': {type: 'const', value: '#38B48B'}, // @ひすいいろ
  '秘色色': {type: 'const', value: '#ABCED8'}, // @ひそくいろ
  '人色': {type: 'const', value: '#F1BF99'}, // @ひといろ
  '一重梅': {type: 'const', value: '#DE8397'}, // @ひとえうめ
  '向日葵色': {type: 'const', value: '#FCC800'}, // @ひまわりいろ
  '鶸色': {type: 'const', value: '#D7CF3A'}, // @ひわいろ
  '檜皮色': {type: 'const', value: '#965036'}, // @ひわだいろ
  '鶸茶': {type: 'const', value: '#8C8861'}, // @ひわちゃ
  '鶸萌黄': {type: 'const', value: '#82AE46'}, // @ひわもえぎ
  '白群': {type: 'const', value: '#83CCD2'}, // @びゃくぐん
  '白緑': {type: 'const', value: '#D6E9CA'}, // @びゃくろく
  '天鵞絨': {type: 'const', value: '#2F5D50'}, // @びろうど
  '枇杷茶': {type: 'const', value: '#AE7C4F'}, // @びわちゃ
  '檳榔子染': {type: 'const', value: '#433D3C'}, // @びんろうじぞめ
  '深川鼠': {type: 'const', value: '#97A791'}, // @ふかがわねずみ
  '深緑': {type: 'const', value: '#00552E'}, // @ふかみどり
  '深紫': {type: 'const', value: '#493759'}, // @ふかむらさき
  '柴染': {type: 'const', value: '#B28C6E'}, // @ふしぞめ
  '藤色': {type: 'const', value: '#BBBCDE'}, // @ふじいろ
  '藤煤竹': {type: 'const', value: '#5A5359'}, // @ふじすすたけ
  '藤納戸': {type: 'const', value: '#706CAA'}, // @ふじなんど
  '藤鼠': {type: 'const', value: '#A6A5C4'}, // @ふじねず
  '藤紫': {type: 'const', value: '#A59ACA'}, // @ふじむらさき
  '二藍': {type: 'const', value: '#915C8B'}, // @ふたあい
  '葡萄色': {type: 'const', value: '#522F60'}, // @ぶどういろ
  '葡萄鼠': {type: 'const', value: '#705B67'}, // @ぶどうねずみ
  '鼈甲色': {type: 'const', value: '#DE9A41'}, // @べっこういろ
  '紅赤': {type: 'const', value: '#D9333F'}, // @べにあか
  '紅鬱金': {type: 'const', value: '#CB8347'}, // @べにうこん
  '紅海老茶': {type: 'const', value: '#A73836'}, // @べにえびちゃ
  '紅掛空色': {type: 'const', value: '#8491C3'}, // @べにかけそらいろ
  '紅掛花色': {type: 'const', value: '#68699B'}, // @べにかけはないろ
  '紅樺色': {type: 'const', value: '#BB5548'}, // @べにかばいろ
  '紅桔梗': {type: 'const', value: '#4D4398'}, // @べにききょう
  '紅消鼠': {type: 'const', value: '#524748'}, // @べにけしねずみ
  '紅鳶': {type: 'const', value: '#9A493F'}, // @べにとび
  '紅緋': {type: 'const', value: '#E83929'}, // @べにひ
  '紅檜皮': {type: 'const', value: '#7B4741'}, // @べにひはだ
  '紅藤色': {type: 'const', value: '#CCA6BF'}, // @べにふじいろ
  '紅碧': {type: 'const', value: '#8392C2'}, // @べにみどり
  '紅紫': {type: 'const', value: '#B44C97'}, // @べにむらさき
  '弁柄色': {type: 'const', value: '#8F2E14'}, // @べんがらいろ
  '本紫': {type: 'const', value: '#65318E'}, // @ほんむらさき
  '牡丹色': {type: 'const', value: '#E7609E'}, // @ぼたんいろ
  '牡丹鼠': {type: 'const', value: '#D3CCD6'}, // @ぼたんねず
  '舛花色': {type: 'const', value: '#5B7E91'}, // @ますはないろ
  '真朱': {type: 'const', value: '#EC6D71'}, // @まそお
  '真赭': {type: 'const', value: '#D57C6B'}, // @まそほ
  '抹茶色': {type: 'const', value: '#C5C56A'}, // @まっちゃいろ
  '松葉色': {type: 'const', value: '#839B5C'}, // @まつばいろ
  '豆殻茶': {type: 'const', value: '#8B968D'}, // @まめがらちゃ
  '蜜柑色': {type: 'const', value: '#F08300'}, // @みかんいろ
  '水浅葱': {type: 'const', value: '#80ABA9'}, // @みずあさぎ
  '水色': {type: 'const', value: '#BCE2E8'}, // @みずいろ
  '水柿': {type: 'const', value: '#E4AB9B'}, // @みずがき
  '翠': {type: 'const', value: '#3EB370'}, // @みどり
  '湊鼠': {type: 'const', value: '#80989B'}, // @みなとねずみ
  '海松色': {type: 'const', value: '#726D40'}, // @みるいろ
  '海松茶': {type: 'const', value: '#5A544B'}, // @みるちゃ
  '槿色': {type: 'const', value: '#775580'}, // @むくげいろ
  '虫襖': {type: 'const', value: '#3A5B52'}, // @むしあお
  '蒸栗色': {type: 'const', value: '#EBE1A9'}, // @むしぐりいろ
  '紫': {type: 'const', value: '#884898'}, // @むらさき
  '紫水晶': {type: 'const', value: '#E7E7EB'}, // @むらさきすいしょう
  '紫鳶': {type: 'const', value: '#5F414B'}, // @むらさきとび
  '紫鼠': {type: 'const', value: '#71686C'}, // @むらさきねず
  '萌黄': {type: 'const', value: '#AACF53'}, // @もえぎ
  '萌葱色': {type: 'const', value: '#006E54'}, // @もえぎいろ
  '木蘭色': {type: 'const', value: '#C7B370'}, // @もくらんじき
  '桃色': {type: 'const', value: '#F09199'}, // @ももいろ
  '百入茶': {type: 'const', value: '#1F3134'}, // @ももしおちゃ
  '桃花色': {type: 'const', value: '#E198B4'}, // @ももはないろ
  '柳色': {type: 'const', value: '#A8C97F'}, // @やなぎいろ
  '柳煤竹': {type: 'const', value: '#5B6356'}, // @やなぎすすたけ
  '柳染': {type: 'const', value: '#93B881'}, // @やなぎぞめ
  '柳茶': {type: 'const', value: '#A1A46D'}, // @やなぎちゃ
  '柳鼠': {type: 'const', value: '#C8D5BB'}, // @やなぎねず
  '山鳩色': {type: 'const', value: '#767C6B'}, // @やまばといろ
  '山吹色': {type: 'const', value: '#F8B500'}, // @やまぶきいろ
  '山吹茶': {type: 'const', value: '#C89932'}, // @やまぶきちゃ
  '山桃色': {type: 'const', value: '#B38000'}, // @やまももいろ
  '雄黄': {type: 'const', value: '#F9C89B'}, // @ゆうおう
  '許色': {type: 'const', value: '#E1A9AB'}, // @ゆるしいろ
  '羊羹色': {type: 'const', value: '#383C3C'}, // @ようかんいろ
  '駱駝色': {type: 'const', value: '#BF794E'}, // @らくだいろ
  '璃寛茶': {type: 'const', value: '#6A5D21'}, // @りかんちゃ
  '利休色': {type: 'const', value: '#8F8667'}, // @りきゅういろ
  '利休白茶': {type: 'const', value: '#B3ADA0'}, // @りきゅうしろちゃ
  '利休茶': {type: 'const', value: '#A59564'}, // @りきゅうちゃ
  '利休鼠': {type: 'const', value: '#888E7E'}, // @りきゅうねずみ
  '緑黄色': {type: 'const', value: '#DCCB18'}, // @りょくおうしょく
  '竜胆色': {type: 'const', value: '#9079AD'}, // @りんどういろ
  '瑠璃色': {type: 'const', value: '#1E50A2'}, // @るりいろ
  '瑠璃紺': {type: 'const', value: '#19448E'}, // @るりこん
  '煉瓦色': {type: 'const', value: '#B55233'}, // @れんがいろ
  '蝋色': {type: 'const', value: '#2B2B2B'}, // @ろういろ
  '緑青色': {type: 'const', value: '#47885E'}, // @ろくしょういろ
  '路考茶': {type: 'const', value: '#8C7042'}, // @ろこうちゃ
  '若草色': {type: 'const', value: '#C3D825'}, // @わかくさいろ
  '若竹色': {type: 'const', value: '#68BE8D'}, // @わかたけいろ
  '若菜色': {type: 'const', value: '#D8E698'}, // @わかないろ
  '若苗色': {type: 'const', value: '#C7DC68'}, // @わかなえいろ
  '若葉色': {type: 'const', value: '#B9D08B'}, // @わかばいろ
  '若緑': {type: 'const', value: '#98D98E'}, // @わかみどり
  '若紫': {type: 'const', value: '#BC64A4'}, // @わかむらさき
  '若芽色': {type: 'const', value: '#E0EBAF'}, // @わかめいろ
  '山葵色': {type: 'const', value: '#A8BF93'}, // @わさびいろ
  '勿忘草色': {type: 'const', value: '#89C3EB'}, // @わすれなぐさいろ
  '透明': {type: 'const', value: 'rgba(0,0,0,0)'}, // @とうめい
}
// モジュールのエクスポート(必ず必要)
if (typeof module !== 'undefined' && module.exports) {
  module.exports = TraditionalColor
}
//プラグインの自動登録
if (typeof (navigator) === 'object') {
  navigator.nako3.addPluginObject('TraditionalColor', TraditionalColor)
}
